In [415]:
import numpy as np
import pandas as pd
import string
import pickle
import operator
import matplotlib.pyplot as plt
%matplotlib inline

In [416]:
with open("jpn.txt", 'r', encoding='utf-8') as f:
    lines = f.read().split('\n')

In [417]:
input_texts = []
target_texts = []
target_text_2=[]
bos = "<BOS> "
eos = " <EOS>"

for line in lines:
    if len(line.split("\t")) == 2:
        input_text, target_text = line.split("\t")[0], line.split("\t")[1]
        target_text_2.append(target_text)
        target_text = bos + target_text + eos
        input_texts.append(input_text)
        target_texts.append(target_text)

len(input_texts)

43953

In [456]:
input_data=input_texts[0:100]
output_data=target_text_2[:100]
out2=target_texts[:100]

In [457]:
print(input_data[:1])
print(output_data[:1])
print(out2[:1])

['Go.']
['行け。']
['<BOS> 行け。 <EOS>']


In [458]:
# input_texts=input_texts[1:5]
# target_texts=target_texts[1:5]
# target_text_2=target_text_2[1:5]

In [459]:
# target_texts

In [460]:
# from keras.utils import to_categorical
# Y=to_categorical(Y_train)
# Y.shape

In [481]:
>>> from tensorflow.keras.preprocessing.text import Tokenizer
>>> from tensorflow.keras.preprocessing.sequence import pad_sequences
maxlen=20
tokenizer_input_data = Tokenizer(num_words=1000,char_level=True)
tokenizer_input_data.fit_on_texts(input_data)
def encoding(tokenizer_input_data,sentenc):
#     print(sentenc)
    res=[]
    for sent in sentenc:
        sent=sent.lower()
        r=[]
        for char in sent:
#             print(char)
            r.append(tokenizer_input_data.word_index[char])
        res.append(r)
    return np.array(res)
X_train = encoding(tokenizer_input_data,input_data)#tokenizer_input_data.texts_to_sequences(input_data)
# X_test = tokenizer.texts_to_sequences(sentences_test)

    # Adding 1 because of reserved 0 index
vocab_size_input_data = len(tokenizer_input_data.word_index) + 1

    # Pad sequences with zeros
encoder_input___ = pad_sequences(X_train, padding='post', maxlen=maxlen)

C:\Users\Vision\.conda\envs\Tensor\lib\site-packages\ipykernel_launcher.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  app.launch_new_instance()


In [482]:
encoder_input___.shape

(100, 20)

In [462]:
print(tokenizer_input_data.word_index)
print(encoder_input[:3])

{' ': 1, '.': 2, 'o': 3, 'e': 4, 'i': 5, '!': 6, 'n': 7, 'w': 8, 'h': 9, 't': 10, 'r': 11, 'l': 12, 'u': 13, 'm': 14, 's': 15, 'p': 16, 'y': 17, 'g': 18, 'a': 19, 'j': 20, 'k': 21, '?': 22, 'f': 23, "'": 24, 'x': 25, 'q': 26, 'c': 27, 'z': 28, '1': 29, '9': 30}
[[18  3  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [18  3  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 9  5  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [463]:
>>> from tensorflow.keras.preprocessing.text import Tokenizer
>>> from tensorflow.keras.preprocessing.sequence import pad_sequences
maxlen=20
tokenizer_output = Tokenizer(num_words=1000,char_level=True)
tokenizer_output.fit_on_texts(output_data)
Y_train = encoding(tokenizer_output,output_data)#tokenizer_Y.texts_to_sequences(target_texts)
# X_test = tokenizer.texts_to_sequences(sentences_test)

    # Adding 1 because of reserved 0 index
vocab_size_output = len(tokenizer_output.word_index) + 1

    # Pad sequences with zeros
Y_train_out = pad_sequences(Y_train, padding='post', maxlen=maxlen)
# X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

C:\Users\Vision\.conda\envs\Tensor\lib\site-packages\ipykernel_launcher.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  app.launch_new_instance()


In [464]:
print(Y_train_out[:5])

[[46 29  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [46 16  7 17  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [30  4 47 24  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [18  9 25 13 19  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [39 48  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [465]:
maxlen=20
tokenizer_out2 = Tokenizer(num_words=1000,char_level=True)
tokenizer_out2.fit_on_texts(out2)
Y_traint = encoding(tokenizer_out2,out2)#tokenizer_out2.texts_to_sequences(target_text_2)
# X_test = tokenizer.texts_to_sequences(sentences_test)

    # Adding 1 because of reserved 0 index
vocab_size_out2 = len(tokenizer_out2.word_index) + 1

    # Pad sequences with zeros
Y_train_out2 = pad_sequences(Y_traint, padding='post', maxlen=maxlen)

C:\Users\Vision\.conda\envs\Tensor\lib\site-packages\ipykernel_launcher.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  app.launch_new_instance()


In [466]:
print(Y_train_out2[:5])


[[ 1  6  2  3  4  5 53 36  8  5  1  7  2  3  4  0  0  0  0  0]
 [ 1  6  2  3  4  5 53 23 14 24 15  8  5  1  7  2  3  4  0  0]
 [ 1  6  2  3  4  5 37 11 54 31  8  5  1  7  2  3  4  0  0  0]
 [ 1  6  2  3  4  5 25 16 32 20 26  9  5  1  7  2  3  4  0  0]
 [ 1  6  2  3  4  5 46 55  8  5  1  7  2  3  4  0  0  0  0  0]]


In [493]:
out_one_hot_encoding=to_categorical(Y_train_out)

In [495]:
len(tokenizer_out2.word_index)
out_one_hot_encoding.shape

(100, 20, 127)

In [505]:
latent_dim=50
# maxlen=32
%config Completer.use_jedi = False
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras import layers
from keras.layers import Input,Embedding,LSTM,Dense
encoder_inputs = Input(shape=(maxlen,))
x = Embedding(vocab_size_input_data, latent_dim)(encoder_inputs)
x, state_h, state_c = LSTM(32,
                           return_state=True)(x)
encoder_states = [state_h, state_c]

# Set up the decoder, using `encoder_states` as initial state.
decoder_inputs = Input(shape=(20,))
xe = Embedding(vocab_size_out2, latent_dim)(decoder_inputs)
decoder_lstm = LSTM(units=32, return_sequences=True, return_state=True)
decoding_inputs,h,c=decoder_lstm(xe, initial_state=encoder_states)

decoder_outputs = Dense(vocab_size_out2, activation='softmax')(decoding_inputs)

# Define the model that will turn
# `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

In [506]:
model.compile(optimizer='adam', loss='categorical_crossentropy')
model.summary()

Model: "model_48"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_63 (InputLayer)           [(None, 20)]         0                                            
__________________________________________________________________________________________________
input_64 (InputLayer)           [(None, 20)]         0                                            
__________________________________________________________________________________________________
embedding_54 (Embedding)        (None, 20, 50)       1550        input_63[0][0]                   
__________________________________________________________________________________________________
embedding_55 (Embedding)        (None, 20, 50)       6700        input_64[0][0]                   
___________________________________________________________________________________________

In [504]:
vocab_size_output

127

In [501]:
# model.compile(optimizer='rmsprop', loss='categorical_crossentropy')
# model.summary()

In [507]:
model.fit([encoder_input___,Y_train_out2],out2_one_hot_encoding)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
4/4 [==============================] - 8s 51ms/step - loss: 4.8948


In [522]:
preditctions=model.predict([encoder_input___[:1],test]).argmax(axis=2)

In [538]:
preditctions[:,19][0]

2

In [542]:
for i in range(1, 20):
    
    output = model.predict([encoder_input___[:1], test]).argmax(axis=2)
    print("::::::::::",test.shape)
    test[:,i] = output[:,i]
#     print("...................",decoder_input[0,1:])

:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)
:::::::::: (1, 20)


In [543]:
test[0, 1:]

array([ 1,  2,  1,  5,  1,  1,  1,  1,  1,  1, 14,  1,  1,  5,  1,  1,  1,
        5, 13])

In [544]:
Y_train_out2[0:1]

array([[ 1,  6,  2,  3,  4,  5, 53, 36,  8,  5,  1,  7,  2,  3,  4,  0,
         0,  0,  0,  0]])

In [512]:
# len(tokenizer_out2.word_index)
test=encoding(tokenizer_out2,["<BOS>"])
test=pad_sequences(test,padding="post",maxlen=20)
test

array([[1, 6, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [123]:
Y_decode=[]
for y in Y_train:
    a=list([0])+list(y[:-18])
    Y_decode.append(a)
Y_decode=np.array(Y_decode)
Y_decode=pad_sequences(Y_decode,padding='post',maxlen=20)
Y_decode

array([[0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [283]:
# Y.shape
# Y[0:3]
Y=to_categorical(Y_train,num_classes=7)

In [289]:
Y

array([[[0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1

In [307]:
model.fit([X_train[0:3],Y_train_d[0:3]],Y[0:3],epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0746
Epoch 2/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0733
Epoch 3/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0723
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0715
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0708
Epoch 6/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0702
Epoch 7/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0696
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0690
Epoch 9/100
1/1 [==============================] - 0s 29ms/step - loss: 0.0685
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 0.0680
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0675
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0670
Epoch 13/100
1/1 [==============================]

In [306]:
Y_train_d

array([[1, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
Y.shape

(4, 20, 7)

In [311]:
encoder_model = Model(encoder_inputs, encoder_states)
decoder_state_input_h = Input(shape=(32,))
decoder_state_input_c = Input(shape=(32,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
l= Embedding(vocab_size+100, 50)(decoder_inputs)
# xx = LSTM(50, return_sequences=True)(deco)
# decoder_outputs, state_h, state_c = decoder_lstm(x, initial_state=decoder_states_inputs)
# decoder_states = [state_h, state_c]
dec,state_h,state_c=decoder_lstm(l,initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_dense = Dense(vocab_size_Y, activation='softmax')
decoder_outputs = decoder_dense(dec)
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

In [312]:
decoder_model.summary()

Model: "model_43"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_48 (InputLayer)           [(None, 20)]         0                                            
__________________________________________________________________________________________________
embedding_43 (Embedding)        (None, 20, 50)       5200        input_48[0][0]                   
__________________________________________________________________________________________________
input_53 (InputLayer)           [(None, 32)]         0                                            
__________________________________________________________________________________________________
input_54 (InputLayer)           [(None, 32)]         0                                            
___________________________________________________________________________________________

In [365]:
p=encoder_model.predict(X_train[3:4])
p

[array([[ 0.8577198 ,  0.9449405 ,  0.9282536 ,  0.4607314 ,  0.9573481 ,
         -0.6842728 , -0.9539095 , -0.93779564, -0.8468385 , -0.9242322 ,
         -0.9328484 , -0.56108254, -0.95391804,  0.04184075,  0.9619946 ,
         -0.9362941 , -0.90437865, -0.86949646,  0.9710316 ,  0.6820846 ,
         -0.8933834 ,  0.9269029 ,  0.68682915,  0.15373339, -0.95877755,
         -0.38698614, -0.95077384,  0.95374453,  0.11238529,  0.12849942,
          0.94676965, -0.93532735]], dtype=float32),
 array([[ 3.8805337 ,  2.9743915 ,  7.205372  ,  1.3049401 ,  7.3965306 ,
         -0.8787402 , -4.120671  , -3.9354963 , -4.652177  , -4.951768  ,
         -3.6575956 , -0.69329846, -5.810089  ,  3.557444  ,  3.053109  ,
         -9.698375  , -2.9121366 , -3.2035367 ,  5.728649  ,  0.9334122 ,
         -1.769656  ,  2.3676617 ,  2.2727256 ,  5.899751  , -6.7664843 ,
         -6.677766  , -8.389059  ,  5.070927  ,  5.360142  ,  0.41647035,
          3.536964  , -6.0416083 ]], dtype=float32)]

In [366]:
Y

array([[[0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1

In [407]:
target_seq = np.zeros((1, 7))
target_seq[0][0]=1
# target_seq[0][1]=3
target_seq

array([[1., 0., 0., 0., 0., 0., 0.]])

In [408]:
target_texts

['<BOS> 行きなさい。 <EOS>',
 '<BOS> やっほー。 <EOS>',
 '<BOS> こんにちは！ <EOS>',
 '<BOS> 走れ。 <EOS>']

In [409]:
targ=Y_train[0].reshape(1,20)
tt=Y_decode[0].reshape(1,20)
tt

array([[0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [410]:
prediction,_,_=decoder_model.predict([target_seq]+p)

ValueError: Input 0 is incompatible with layer model_43: expected shape=(None, 20), found shape=(None, 7)

In [411]:
tokenizer_Y.word_index

{'<bos>': 1, '<eos>': 2, '行きなさい。': 3, 'やっほー。': 4, 'こんにちは！': 5, '走れ。': 6}

In [405]:
np.argmax(prediction[0,-16, :])

2

In [392]:
prediction[0,-1, :]

array([0.11406721, 0.10966454, 0.27772433, 0.07411416, 0.23812605,
       0.01641841, 0.16988535], dtype=float32)

In [382]:
prediction.shape

(1, 20, 7)

In [351]:
tokenizer_Y.word_index

{'<bos>': 1, '<eos>': 2, '行きなさい。': 3, 'やっほー。': 4, 'こんにちは！': 5, '走れ。': 6}

In [352]:
target_text[1]

'B'